game:
  maxplayer: 100000
  reloadpath: 
  sendlog: true #发送log
  platform: 
    key: 72a489ca35e69b73741795d6aaec6982
    host: http://pc.majiangworld.com/elect/app/index.php
    version: 1.0
  useport: true
  test: false
  

server:
  port: 8099
  
---
spring:
  application:
    name: WX_PLATFORM
---    
spring:
    mvc:
      view:
        # 页面默认前缀目录
        prefix: /WEB-INF/jsp/
        # 响应页面默认后缀
        suffix: .jsp